# Site Info
title:              ":p"
description:        ":p的丘丘空间"
author_name:        "ᴢʜᴀɴɢ" # change this to your name
logo_url:           /assets/avatar.jpg #https://aroucc.oss-cn-hangzhou.aliyuncs.com/images/avatar.jpg

# Site Settings
url:                https://disbb.com # main url
baseurl:            
#permalink:          /:title
timezone:           Asia/Shanghai # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true # enables support for mathjax - set to 'false' to disable
future:             true

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

paginate: 10
paginate_path: "index/:num"

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap
  - jekyll-paginate

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
